version: "3.9"
services:
  web:
    container_name: hrsd_api
    build: .
    volumes:
      - ./app:/src/app
    command: bash -c "python app/db_migrator.py && python app/main.py"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:13.4-alpine
    container_name: hrsd_db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"

volumes:
  db_data:
